### PR TITLE
This branch is 13 commits ahead of odoo-brazil:develop.

### PR DESCRIPTION
**Pull request by cmsalmeida**
This branch is 13 commits ahead of odoo-brazil:develop.
I just wanted to get latest version form odoo-brazil, into my forked branches, I did a git pull upstream develop.
I suppose with this pulling I get in sync with odoo-brazil one.

I have a fork of odoo-brazil/account-fiscal-rule in my github account, and a clone thinkopensolutions/account-fiscal-rule

### CODE REVIEW

**Comment by danimaribeiro** [comment]
You have to fix the merge conflicts in your repo.
Why did you create this Pull Request?

**Comment by cmsalmeida** [comment]
Hi
I did to get even message in my fork.
What will be the correct procedure?
Thanks ...

**Comment by cmsalmeida** [comment]
I will drop my fork and create again.
Sorry for any inconvenience.
After fork and clone again I will try another pull request. Hope to get it right then.
Regards

**Comment by danimaribeiro** [comment]
When you open the pull request page, you have swap the branchs here. Then you can get the changes from the main repo.
forks

**Pull request closed without merging**
